FROM node:20-alpine
RUN npm install -g pnpm
WORKDIR /app

COPY frontend/package.json frontend/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY frontend/ .

# --- ESTO ES LO QUE ESTÁ FALTANDO ---
ARG NEXT_PUBLIC_STRAPI_URL
ENV NEXT_PUBLIC_STRAPI_URL=$NEXT_PUBLIC_STRAPI_URL
# ------------------------------------

RUN pnpm run build

EXPOSE 3001
CMD ["pnpm", "start"]